[platformio]
default_envs = ota-lan

[env]
platform = espressif32
framework = espidf

board = ezq-ctlr-b
board_build.variants_dir = boards
board_build.board = ezq-ctlr-b
board_build.partitions = partitions/partition_4MB.csv
board_build.filesystem = spiffs

monitor_speed = 115200

[env:uart-bootstrap]
upload_protocol = esptool
upload_speed = 115200
upload_port = COM5

[env:ota-lan]
upload_protocol = custom
upload_flags =
  --host
  192.168.0.199
  --port
  8032
upload_command = python "$PROJECT_DIR/utils/ota_upload.py" $UPLOAD_FLAGS --image $SOURCE
