[platformio]
default_envs = ota-lan
data_dir = settings

[env]
platform = espressif32
framework = espidf

board = ezq-ctlr-b
board_build.variants_dir = boards
board_build.board = ezq-ctlr-b
board_build.partitions = partitions/partition_4MB.csv
board_build.filesystem = spiffs

monitor_speed = 115200

[env:uart-bootstrap]
upload_protocol = esptool
upload_speed = 115200
upload_port = COM5

[env:ota-lan]
extra_scripts = post:extra_scripts/settings_fs.py
upload_protocol = custom
custom_ota_host = 192.168.0.199
custom_ota_port = 8032
custom_settings_partition = settings
custom_web_ui_partition = web_ui
upload_command = python "$PROJECT_DIR/utils/ota_upload.py" --host ${this.custom_ota_host} --port ${this.custom_ota_port} --filesystem-partition ${this.custom_settings_partition} --image $SOURCE
